package com.maden.filmlist.domain.model.movie_detail

import com.maden.filmlist.data.local.model.MovieDetailDaoModel
import com.maden.filmlist.data.remote.model.movie_detail.MovieDetailResponseDto

data class MovieDetailResponseModel(
    val adult: Boolean?,
    val backdropPath: String?,
    val belongsToCollection: BelongsToCollectionModel?,
    val budget: Double?,
    val genre: List<GenreModel>?,
    val homepage: String?,
    val id: Double?,
    val imdbId: String?,
    val originCountry: List<String>?,
    val originalLanguage: String?,
    val originalTitle: String?,
    val overview: String?,
    val popularity: Double?,
    val posterPath: String?,
    val productionCompanies: List<ProductionCompanyModel>?,
    val productionCountries: List<ProductionCountryModel>?,
    val releaseDate: String?,
    val revenue: Double?,
    val runtime: Double?,
    val spokenLanguages: List<SpokenLanguageModel>?,
    val status: String?,
    val tagline: String?,
    val title: String?,
    val video: Boolean?,
    val voteAverage: Double?,
    val voteCount: Double?,
)

fun MovieDetailResponseDto.toModel(): MovieDetailResponseModel {
    return MovieDetailResponseModel(
        adult = adult,
        backdropPath = backdrop_path,
        belongsToCollection = belongs_to_collection?.toModel(),
        budget = budget,
        genre = genreDtos?.map { it.toModel() },
        homepage = homepage,
        id = id,
        video = video,
        voteAverage = vote_average,
        voteCount = vote_count,
        title = title,
        tagline = tagline,
        status = status,
        runtime = runtime,
        spokenLanguages = spoken_languages?.map { it.toModel() },
        productionCountries = production_countries?.map { it.toModel() },
        productionCompanies = production_companies?.map { it.toModel() },
        posterPath = poster_path,
        popularity = popularity,
        originalTitle = original_title,
        overview = overview,
        originalLanguage = original_language,
        originCountry = origin_country,
        imdbId = imdb_id,
        revenue = revenue,
        releaseDate = release_date,
    )
}

fun MovieDetailDaoModel.toModel(): MovieDetailResponseModel {
    return MovieDetailResponseModel(
        id = id.toDouble(),
        title = title,
        overview = overview,
        posterPath = posterPath,
        voteCount = voteCount,
        adult = adult,
        backdropPath = backdropPath,
        belongsToCollection = null,
        budget = budget,
        genre = null,
        homepage = homepage,
        imdbId = imdbId,
        tagline = tagline,
        status = status,
        runtime = runtime,
        spokenLanguages = null,
        popularity = popularity,
        video = video,
        voteAverage = voteAverage,
        revenue = revenue,
        releaseDate = releaseDate,
        originalLanguage = originalLanguage,
        originalTitle = originalTitle,
        originCountry = null,
        productionCompanies = null,
        productionCountries = null,
    )
}